"""Add icon count fields to Post

Revision ID: baa5cfc4bb5f
Revises: b019b739ae86
Create Date: 2024-10-24 17:40:47.605798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa5cfc4bb5f'
down_revision = 'b019b739ae86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon1_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('icon2_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('icon3_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('icon3_count')
        batch_op.drop_column('icon2_count')
        batch_op.drop_column('icon1_count')

    # ### end Alembic commands ###
